### ISSUE TITLE
Verification client/server certificates

### ISSUE THREAD

**Issue by jkralik** [pions/dtls#20]
Hi. 
Is there any plan to add support for setup certification authority (intermediate) to verify client/server certificates? 
Thx

**Comment by Sean-Der** [comment]
Hey @jkralik 

You can call [RemoteCertificate](https://godoc.org/github.com/pions/dtls/pkg/dtls#Conn.RemoteCertificate)

We currently don't send a certificate request (but we can respond to them) I would love to see the API extended to support setting/getting extensions (like SRTP) and enabling `Certificate Request` when you are Dialing!

**Comment by Sean-Der** [comment]
Hey @jkralik 

I am closing this for now, but please feel free to re-open if we need to do more so you can implement what you are working on!

thanks
